idf_component_register(
    SRCS
        "main.c"
        "ui.c"
        "wifi_at.cpp"
    INCLUDE_DIRS
        "."
    REQUIRES
        freertos
        driver
        esp_lcd
        rm69a10
        esp_hw_support
        esp_timer
        esp_eth
        esp_netif
        esp_event
        esp_http_client
        nvs_flash
        newlib
        lwip
        esp_adc
        sdmmc
        esp_driver_sdmmc
        fatfs
        vfs
        lvgl__lvgl
        esp_system
        esp_driver_i2s
        mbedtls
        cpp_bus_driver
)
