idf_component_register(
    SRCS
        "main.c"
        "ui.c"
    INCLUDE_DIRS
        "."
    REQUIRES
        freertos
        driver
        esp_lcd
        rm69a10
        esp_hw_support
        esp_timer
        esp_eth
        esp_netif
        esp_event
        esp_http_client
        nvs_flash
        newlib
        lwip
        esp_adc
        lvgl__lvgl
)
